#!/bin/sh

#script from https://daveceddia.com/deploy-git-repo-to-server/
# Check out the files
git --work-tree=/var/www/equitable-syllabus-project --git-dir=/var/www/equitable-syllabus-project.git checkout -f

(cd /var/www/equitable-syllabus-project && npm run build)
